1.2.1.1
2 cond 1,16_8,8_16,6,24,3 with duplicate conv and batchnorm batchsize=4 epochs=200
Importing finished!!
cuda is going to be used!!
Dataset loaded!! Length (train dataset) - 6880
----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
================================================================
            Conv2d-1              [-1, 8, 8, 8]              80
       BatchNorm2d-2              [-1, 8, 8, 8]              16
            Conv2d-3              [-1, 8, 8, 8]             584
              ReLU-4              [-1, 8, 8, 8]               0
            Conv2d-5             [-1, 16, 6, 6]           1,168
       BatchNorm2d-6             [-1, 16, 6, 6]              32
            Conv2d-7             [-1, 16, 6, 6]           2,320
              ReLU-8             [-1, 16, 6, 6]               0
            Conv2d-9             [-1, 24, 3, 3]           3,480
      BatchNorm2d-10             [-1, 24, 3, 3]              48
           Conv2d-11             [-1, 24, 3, 3]           5,208
             ReLU-12             [-1, 24, 3, 3]               0
          Flatten-13                  [-1, 216]               0
================================================================
Total params: 12,936
Trainable params: 12,936
Non-trainable params: 0
----------------------------------------------------------------
Input size (MB): 0.00
Forward/backward pass size (MB): 0.04
Params size (MB): 0.05
Estimated Total Size (MB): 0.09
----------------------------------------------------------------
None
Task: v2lr, Epoch:1, Loss:0.001469              		Task: InvProb, Epoch:1, Loss:0.000332
Task: v2lr, Epoch:11, Loss:0.001127              		Task: InvProb, Epoch:11, Loss:0.000364
Task: v2lr, Epoch:21, Loss:0.000642              		Task: InvProb, Epoch:21, Loss:0.000210
Task: v2lr, Epoch:31, Loss:0.000522              		Task: InvProb, Epoch:31, Loss:0.000177
Task: v2lr, Epoch:41, Loss:0.000398              		Task: InvProb, Epoch:41, Loss:0.000133
Task: v2lr, Epoch:51, Loss:0.000570              		Task: InvProb, Epoch:51, Loss:0.000178
Task: v2lr, Epoch:61, Loss:0.000437              		Task: InvProb, Epoch:61, Loss:0.000148
Task: v2lr, Epoch:71, Loss:0.000453              		Task: InvProb, Epoch:71, Loss:0.000142
Task: v2lr, Epoch:81, Loss:0.000423              		Task: InvProb, Epoch:81, Loss:0.000133
Task: v2lr, Epoch:91, Loss:0.000479              		Task: InvProb, Epoch:91, Loss:0.000145
Task: v2lr, Epoch:101, Loss:0.000425              		Task: InvProb, Epoch:101, Loss:0.000129
Task: v2lr, Epoch:111, Loss:0.000416              		Task: InvProb, Epoch:111, Loss:0.000131
Task: v2lr, Epoch:121, Loss:0.000382              		Task: InvProb, Epoch:121, Loss:0.000122
Task: v2lr, Epoch:131, Loss:0.000372              		Task: InvProb, Epoch:131, Loss:0.000124
Task: v2lr, Epoch:141, Loss:0.000515              		Task: InvProb, Epoch:141, Loss:0.000171
Task: v2lr, Epoch:151, Loss:0.000354              		Task: InvProb, Epoch:151, Loss:0.000122
Task: v2lr, Epoch:161, Loss:0.000348              		Task: InvProb, Epoch:161, Loss:0.000118
Task: v2lr, Epoch:171, Loss:0.000475              		Task: InvProb, Epoch:171, Loss:0.000151
Task: v2lr, Epoch:181, Loss:0.000407              		Task: InvProb, Epoch:181, Loss:0.000132
Task: v2lr, Epoch:191, Loss:0.000381              		Task: InvProb, Epoch:191, Loss:0.000125
Task: v2lr, Epoch:200, Loss:0.000461              		Task: InvProb, Epoch:200, Loss:0.000141
Avg Test Loss: 0.0007425494889270509
Max Test Loss: 0.003253684379160404
Min Test Loss: 3.120951805613004e-05
written to: ./models/v2lr/2_1.2.1.1.20231117023937_v2lr.pth
written to: ./models/v2lr/2_1.2.1.1.20231117023937_v2lr.pt
Traceback (most recent call last):
  File "/home/kunet.ae/100053678/eit/autoencoders/v2lr.py", line 125, in <module>
    loss_tracker.loc[id_config] = train_losses
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/home/kunet.ae/100053678/.conda/envs/eit/lib/python3.11/site-packages/pandas/core/indexing.py", line 885, in __setitem__
    iloc._setitem_with_indexer(indexer, value, self.name)
  File "/home/kunet.ae/100053678/.conda/envs/eit/lib/python3.11/site-packages/pandas/core/indexing.py", line 1883, in _setitem_with_indexer
    self._setitem_with_indexer_missing(indexer, value)
  File "/home/kunet.ae/100053678/.conda/envs/eit/lib/python3.11/site-packages/pandas/core/indexing.py", line 2219, in _setitem_with_indexer_missing
    raise ValueError("cannot set a row with mismatched columns")
ValueError: cannot set a row with mismatched columns
